# Generated by Django 6.0.4 on 2026-04-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talksession', '0003_message_user_alter_message_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('moderate_messages', 'Can moderate messages'), ('block users', 'Can block users')]},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('manage_chanells', 'Can manage channels')]},
        ),
    ]
