# Generated by Django 6.0.4 on 2026-04-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talksession', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('moderate_messages', 'Can moderate messages'), ('block_users', 'Can block users')]},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('manage_channels', 'Can manage channels')]},
        ),
    ]
