# Generated by Django 6.0.4 on 2026-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talksession', '0010_message_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='message_audio/'),
        ),
    ]
