# Generated by Django 6.0.4 on 2026-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talksession', '0011_message_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'permissions': [('moderate_messages', 'Can moderate messages'), ('block_users', 'Can block users')]},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
